"""initial_schema

Revision ID: 222a60266b0a
Revises:
Create Date: 2026-10-04 19:37:08.350920+00:00
"""

import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

from alembic import op

revision = "222a60266b0a"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("event_type", sa.String(length=64), nullable=False),
        sa.Column("ip_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column(
            "metadata_json",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_audit_events_event_type"), "audit_events", ["event_type"], unique=False)
    op.create_index(op.f("ix_audit_events_user_id"), "audit_events", ["user_id"], unique=False)
    op.create_table(
        "garment_categories",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("slug", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=120), nullable=False),
        sa.Column(
            "group",
            sa.Enum("HEAD", "TOP", "BOTTOM", "SHOES", "WRIST", "OTHER", name="garment_category_group"),
            nullable=False,
        ),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_garment_categories_group"), "garment_categories", ["group"], unique=False)
    op.create_index(op.f("ix_garment_categories_slug"), "garment_categories", ["slug"], unique=True)
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=80), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column(
            "mannequin_presentation", sa.Enum("MALE", "FEMALE", name="mannequin_presentation"), nullable=False
        ),
        sa.Column("email_verified", sa.Boolean(), nullable=False),
        sa.Column("email_verification_token_hash", sa.String(length=64), nullable=True),
        sa.Column("password_reset_token_hash", sa.String(length=64), nullable=True),
        sa.Column("password_reset_expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_table(
        "weather_snapshots",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("location_label", sa.String(length=160), nullable=True),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column(
            "payload",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("provider", sa.String(length=40), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_weather_snapshots_user_id"), "weather_snapshots", ["user_id"], unique=False)
    op.create_table(
        "garments",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("category_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("brand", sa.String(length=120), nullable=True),
        sa.Column("color", sa.String(length=60), nullable=False),
        sa.Column("secondary_colors", sa.JSON(), nullable=False),
        sa.Column("size", sa.String(length=40), nullable=True),
        sa.Column("material", sa.String(length=120), nullable=True),
        sa.Column(
            "season", sa.Enum("ALL", "SPRING", "SUMMER", "AUTUMN", "WINTER", name="season"), nullable=False
        ),
        sa.Column("warmth_level", sa.Integer(), nullable=False),
        sa.Column("waterproof", sa.Boolean(), nullable=False),
        sa.Column("windproof", sa.Boolean(), nullable=False),
        sa.Column("styles", sa.JSON(), nullable=False),
        sa.Column("reference", sa.String(length=160), nullable=True),
        sa.Column("barcode", sa.String(length=32), nullable=True),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column(
            "visual_representation_level",
            sa.Enum("GENERIC", "APPROXIMATE", "EXACT", name="visual_representation_level"),
            nullable=False,
        ),
        sa.Column("asset_key", sa.String(length=255), nullable=True),
        sa.Column("is_archived", sa.Boolean(), nullable=False),
        sa.Column("last_worn_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["category_id"], ["garment_categories.id"], ondelete="RESTRICT"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_garments_barcode"), "garments", ["barcode"], unique=False)
    op.create_index("ix_garments_user_category", "garments", ["user_id", "category_id"], unique=False)
    op.create_index(op.f("ix_garments_user_id"), "garments", ["user_id"], unique=False)
    op.create_table(
        "locations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("label", sa.String(length=160), nullable=False),
        sa.Column("latitude", sa.Float(), nullable=False),
        sa.Column("longitude", sa.Float(), nullable=False),
        sa.Column("is_default", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_locations_user_id"), "locations", ["user_id"], unique=False)
    op.create_table(
        "notification_preferences",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("rain_alerts", sa.Boolean(), nullable=False),
        sa.Column("daily_outfit", sa.Boolean(), nullable=False),
        sa.Column("temperature_alerts", sa.Boolean(), nullable=False),
        sa.Column("push_token", sa.String(length=255), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_notification_preferences_user_id"), "notification_preferences", ["user_id"], unique=True
    )
    op.create_table(
        "outfits",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outfits_user_id"), "outfits", ["user_id"], unique=False)
    op.create_table(
        "recommendations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("origin_label", sa.String(length=160), nullable=True),
        sa.Column("destination_label", sa.String(length=160), nullable=True),
        sa.Column(
            "activity",
            sa.Enum(
                "EVERYDAY",
                "WORK",
                "SCHOOL",
                "SPORT",
                "RESTAURANT",
                "EVENING",
                "DATE",
                "FORMAL_EVENT",
                "TRAVEL",
                "OTHER",
                name="reco_activity",
            ),
            nullable=False,
        ),
        sa.Column(
            "weather_summary",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("accepted", sa.Boolean(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_recommendations_user_id"), "recommendations", ["user_id"], unique=False)
    op.create_table(
        "sessions",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("refresh_token_hash", sa.String(length=64), nullable=False),
        sa.Column("device_name", sa.String(length=120), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("replaced_by_id", sa.Uuid(), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("refresh_token_hash"),
    )
    op.create_index(op.f("ix_sessions_user_id"), "sessions", ["user_id"], unique=False)
    op.create_table(
        "user_preferences",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("preferred_styles", sa.JSON(), nullable=False),
        sa.Column("liked_colors", sa.JSON(), nullable=False),
        sa.Column("avoided_colors", sa.JSON(), nullable=False),
        sa.Column("cold_threshold_celsius", sa.Float(), nullable=True),
        sa.Column("hot_threshold_celsius", sa.Float(), nullable=True),
        sa.Column("learned_warmth_offset", sa.Float(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_preferences_user_id"), "user_preferences", ["user_id"], unique=True)
    op.create_table(
        "garment_identification_candidates",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("garment_id", sa.Uuid(), nullable=False),
        sa.Column(
            "source",
            sa.Enum("MANUAL", "BARCODE", "LABEL_OCR", "PHOTO_VISION", name="identification_source"),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("PENDING", "CONFIRMED", "REJECTED", name="identification_status"),
            nullable=False,
        ),
        sa.Column("confidence", sa.Float(), nullable=False),
        sa.Column(
            "proposed",
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), "postgresql"),
            nullable=False,
        ),
        sa.Column("raw_excerpt", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["garment_id"], ["garments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_garment_identification_candidates_garment_id"),
        "garment_identification_candidates",
        ["garment_id"],
        unique=False,
    )
    op.create_table(
        "garment_images",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("garment_id", sa.Uuid(), nullable=False),
        sa.Column("object_key", sa.String(length=512), nullable=False),
        sa.Column("content_type", sa.String(length=80), nullable=False),
        sa.Column("byte_size", sa.BigInteger(), nullable=False),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["garment_id"], ["garments.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_garment_images_garment_id"), "garment_images", ["garment_id"], unique=False)
    op.create_table(
        "outfit_history",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("outfit_id", sa.Uuid(), nullable=True),
        sa.Column(
            "worn_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("weather_snapshot_id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), nullable=True),
        sa.Column("destination_label", sa.String(length=160), nullable=True),
        sa.Column(
            "activity",
            sa.Enum(
                "EVERYDAY",
                "WORK",
                "SCHOOL",
                "SPORT",
                "RESTAURANT",
                "EVENING",
                "DATE",
                "FORMAL_EVENT",
                "TRAVEL",
                "OTHER",
                name="activity_context",
            ),
            nullable=True,
        ),
        sa.Column("feedback", sa.String(length=40), nullable=True),
        sa.Column("garment_ids", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["outfit_id"], ["outfits.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_outfit_history_outfit_id"), "outfit_history", ["outfit_id"], unique=False)
    op.create_index(op.f("ix_outfit_history_user_id"), "outfit_history", ["user_id"], unique=False)
    op.create_table(
        "outfit_items",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("outfit_id", sa.Uuid(), nullable=False),
        sa.Column("garment_id", sa.Uuid(), nullable=False),
        sa.Column("layer_order", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["garment_id"], ["garments.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["outfit_id"], ["outfits.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("outfit_id", "garment_id", name="uq_outfit_garment"),
    )
    op.create_index(op.f("ix_outfit_items_outfit_id"), "outfit_items", ["outfit_id"], unique=False)
    op.create_table(
        "recommendation_feedback",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "action",
            sa.Enum(
                "LIKE",
                "NOT_TODAY",
                "TOO_HOT",
                "TOO_COLD",
                "DISLIKE_COMBINATION",
                "CHANGE_TOP",
                "CHANGE_BOTTOM",
                "CHANGE_SHOES",
                name="feedback_action",
            ),
            nullable=False,
        ),
        sa.Column("garment_id", sa.Uuid(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendation_feedback_recommendation_id"),
        "recommendation_feedback",
        ["recommendation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_recommendation_feedback_user_id"), "recommendation_feedback", ["user_id"], unique=False
    )
    op.create_table(
        "recommendation_items",
        sa.Column(
            "id", sa.BigInteger().with_variant(sa.Integer(), "sqlite"), autoincrement=True, nullable=False
        ),
        sa.Column("recommendation_id", sa.Uuid(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("garment_ids", sa.JSON(), nullable=False),
        sa.Column("explanations", sa.JSON(), nullable=False),
        sa.Column("breakdown", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["recommendation_id"], ["recommendations.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_recommendation_items_recommendation_id"),
        "recommendation_items",
        ["recommendation_id"],
        unique=False,
    )
    # ### end Alembic commands ###

    # Reference data: garment category catalog (not demo data — required).
    from app.modules.wardrobe.catalog import CATEGORY_SEED

    categories_table = sa.table(
        "garment_categories",
        sa.column("slug", sa.String),
        sa.column("label", sa.String),
        sa.column(
            "group", sa.Enum("HEAD", "TOP", "HANDS", "BOTTOM", "FEET", "OTHER", name="garment_category_group")
        ),
        sa.column("sort_order", sa.Integer),
    )
    op.bulk_insert(
        categories_table,
        [
            {
                "slug": entry["slug"],
                "label": entry["label"],
                "group": entry["group"].name,  # enum stores member names
                "sort_order": i,
            }
            for i, entry in enumerate(CATEGORY_SEED)
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_recommendation_items_recommendation_id"), table_name="recommendation_items")
    op.drop_table("recommendation_items")
    op.drop_index(op.f("ix_recommendation_feedback_user_id"), table_name="recommendation_feedback")
    op.drop_index(op.f("ix_recommendation_feedback_recommendation_id"), table_name="recommendation_feedback")
    op.drop_table("recommendation_feedback")
    op.drop_index(op.f("ix_outfit_items_outfit_id"), table_name="outfit_items")
    op.drop_table("outfit_items")
    op.drop_index(op.f("ix_outfit_history_user_id"), table_name="outfit_history")
    op.drop_index(op.f("ix_outfit_history_outfit_id"), table_name="outfit_history")
    op.drop_table("outfit_history")
    op.drop_index(op.f("ix_garment_images_garment_id"), table_name="garment_images")
    op.drop_table("garment_images")
    op.drop_index(
        op.f("ix_garment_identification_candidates_garment_id"),
        table_name="garment_identification_candidates",
    )
    op.drop_table("garment_identification_candidates")
    op.drop_index(op.f("ix_user_preferences_user_id"), table_name="user_preferences")
    op.drop_table("user_preferences")
    op.drop_index(op.f("ix_sessions_user_id"), table_name="sessions")
    op.drop_table("sessions")
    op.drop_index(op.f("ix_recommendations_user_id"), table_name="recommendations")
    op.drop_table("recommendations")
    op.drop_index(op.f("ix_outfits_user_id"), table_name="outfits")
    op.drop_table("outfits")
    op.drop_index(op.f("ix_notification_preferences_user_id"), table_name="notification_preferences")
    op.drop_table("notification_preferences")
    op.drop_index(op.f("ix_locations_user_id"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_garments_user_id"), table_name="garments")
    op.drop_index("ix_garments_user_category", table_name="garments")
    op.drop_index(op.f("ix_garments_barcode"), table_name="garments")
    op.drop_table("garments")
    op.drop_index(op.f("ix_weather_snapshots_user_id"), table_name="weather_snapshots")
    op.drop_table("weather_snapshots")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_garment_categories_slug"), table_name="garment_categories")
    op.drop_index(op.f("ix_garment_categories_group"), table_name="garment_categories")
    op.drop_table("garment_categories")
    op.drop_index(op.f("ix_audit_events_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_event_type"), table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
